### ISSUE TITLE
`require-sri-for` removed from the SRI spec

### ISSUE THREAD

**Issue by Malvoz** [mikewest/signature-based-sri#12]
Bullet point nr. 3 in the explainer talks about `require-sri-for`  which was removed in https://github.com/w3c/webappsec-subresource-integrity/pull/82.

> Content Security Policy can layer on top of Subresource Integrity to ensure that integrity checks are required for script execution, and specifying a list of acceptable hashes. For example, the policy "`script-src 'sha256-abc' 'sha256-zyx'; require-sri-for script`" would ensure that script executes only when it matches one of the specified hashes, regardless of the server that delivered it.

Not sure if you want to keep the text still, use strikethrough, or simply remove it. ^^

**Comment by yoavweiss** [comment]
FWIW, I'm planning to try and add `require-sri-for` back..

**Comment by mikewest** [comment]
I removed the bullet for the moment. I'll close this, as it's tangential to the signature discussion, but if/when we revive `require-sri-for` I can add it back here as well.
